CREATE DATABASE IF NOT EXISTS VIP;
DROP TABLE IF EXISTS USERS;
USE VIP;

CREATE TABLE USERS (
	userID INT (10) NOT NULL AUTO_INCREMENT,
	userName VARCHAR(100) NOT NULL,
	userMail VARCHAR(100) NOT NULL,
	organization VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL, /* A hashed string */

	PRIMARY KEY (userID)
);

